<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Payload_A" Id="{68e569a0-88d4-46f8-9a9e-3121423266f2}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK Payload_A IMPLEMENTS I_Payload_A
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	nPayload : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Payload_A">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>