<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Payload_B" Id="{8ddd06a1-3223-421e-855f-9bd61f22ab00}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Payload_B IMPLEMENTS I_Payload_B
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	bPayload : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Payload_B">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>